######################################################################
#
# File name : sdram_init_tb_compile.do
# Created on: Wed Jul 19 10:08:02 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
H:\\soft\\modeltech64_2020.4\\win64\\vlib modelsim_lib/work
H:\\soft\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim

H:\\soft\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim/xil_defaultlib

H:\\soft\\modeltech64_2020.4\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

H:\\soft\\modeltech64_2020.4\\win64\\vlog  -incr -work xil_defaultlib  "+incdir+../../../../sdram_control.srcs/sources_1/new" "+incdir+../../../../sdram_control.srcs/sim_1/new" \
"../../../../sdram_control.srcs/sim_1/new/sdr.v" \
"../../../../sdram_control.srcs/sources_1/new/sdram_init.v" \
"../../../../sdram_control.srcs/sim_1/new/sdram_init_tb.v" \


# compile glbl module
H:\\soft\\modeltech64_2020.4\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

