######################################################################
#
# File name : pwm_tb_wave.do
# Created on: Wed Jul 19 10:06:45 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
