######################################################################
#
# File name : hello_tb_wave.do
# Created on: Wed Jul 05 23:47:37 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
