######################################################################
#
# File name : hello_tb_simulate.do
# Created on: Wed Jul 05 23:51:47 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -coverage -fsmdebug -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.hello_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {hello_tb_wave.do}

view wave
view structure
view signals

do {hello_tb.udo}

run 1000ns
