######################################################################
#
# File name : hello_tb_compile.do
# Created on: Wed Jul 05 23:51:45 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
G:\\soft\\modeltech64_2020.4\\win64\\vlib modelsim_lib/work
G:\\soft\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim

G:\\soft\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim/xil_defaultlib

G:\\soft\\modeltech64_2020.4\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

G:\\soft\\modeltech64_2020.4\\win64\\vlog  -incr -work xil_defaultlib  \
"../../../../hello.srcs/sources_1/new/hello.v" \
"../../../../hello.srcs/sim_1/new/hello_tb.v" \


# compile glbl module
G:\\soft\\modeltech64_2020.4\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

