######################################################################
#
# File name : hello_tb_compile.do
# Created on: Thu Jul 06 09:41:29 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
H:\\soft\\modeltech64_2020.4\\win64\\vlib modelsim_lib/work
H:\\soft\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim

H:\\soft\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim/xil_defaultlib

H:\\soft\\modeltech64_2020.4\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

H:\\soft\\modeltech64_2020.4\\win64\\vlog  -incr -work xil_defaultlib  \
"../../../../hello.srcs/sources_1/new/hello.v" \
"../../../../hello.srcs/sim_1/new/hello_tb.v" \


# compile glbl module
H:\\soft\\modeltech64_2020.4\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

