# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: H:/FPGA/souce/27_math/math.srcs/sources_1/ip/fixed_to_float/fixed_to_float.xci
# IP: The module: 'fixed_to_float' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/FPGA/souce/27_math/math.gen/sources_1/ip/fixed_to_float/fixed_to_float_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fixed_to_float'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: H:/FPGA/souce/27_math/math.srcs/sources_1/ip/fixed_to_float/fixed_to_float.xci
# IP: The module: 'fixed_to_float' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/FPGA/souce/27_math/math.gen/sources_1/ip/fixed_to_float/fixed_to_float_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fixed_to_float'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
